admin_panel/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='admin_dashboard'),
    path('articles/', views.ArticlesListView.as_view(), name='admin_articles'),
    path('articles/edit/<pk>', views.ArticleEditView.as_view(), name='admin_edit_article'),
]

article_module/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.ArticlesListView.as_view(), name='articles_list'),
    path('cat/<str:category>', views.ArticlesListView.as_view(), name='articles_by_category_list'),
    path('<pk>/', views.ArticleDetailView.as_view(), name='articles_detail'),
    path('add-article-comment', views.add_article_comment, name='add_article_comment')
]

eshop_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', include('home_module.urls')),
    path('', include('account_module.urls')),
    path('articles/', include('article_module.urls')),
    path('contact-us/', include('contact_module.urls')),
    path('products/', include('product_module.urls')),
    path('user/', include('user_panel_module.urls')),
    path('order/', include('order_module.urls')),
    path('admin/', admin.site.urls),
    path('admin-panel/', include('admin_panel.urls'))
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

article_module/models.py
from django.db import models
from jalali_date import date2jalali
from account_module.models import User


class ArticleCategory(models.Model):
    parent = models.ForeignKey('ArticleCategory', null=True, blank=True, on_delete=models.CASCADE, verbose_name='دسته بندی والد')
    title = models.CharField(max_length=200, verbose_name='عنوان دسته بندی')
    url_title = models.CharField(max_length=200, unique=True, verbose_name='عنوان در url')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'دسته بندی مقاله'
        verbose_name_plural = 'دسته بندی های مقاله'


class Article(models.Model):
    title = models.CharField(max_length=300, verbose_name='عنوان مقاله')
    slug = models.SlugField(max_length=400, db_index=True, allow_unicode=True, verbose_name='عنوان در url')
    image = models.ImageField(upload_to='images/articles', verbose_name='تصویر مقاله')
    short_description = models.TextField(verbose_name='توضیحات کوتاه')
    text = models.TextField(verbose_name='متن مقاله')
    is_active = models.BooleanField(default=True, verbose_name='فعال / غیرفعال')
    selected_categories = models.ManyToManyField(ArticleCategory, verbose_name='دسته بندی ها')
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='نویسنده', null=True, editable=False)
    create_date = models.DateTimeField(auto_now_add=True, editable=False, verbose_name='تاریخ ثبت')

    def __str__(self):
        return self.title

    def get_jalali_create_date(self):
        return date2jalali(self.create_date)

    def get_jalali_create_time(self):
        return self.create_date.strftime('%H:%M')

    class Meta:
        verbose_name = 'مقاله'
        verbose_name_plural = 'مقالات'


class ArticleComment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name='مقاله')
    parent = models.ForeignKey('ArticleComment', null=True, blank=True, on_delete=models.CASCADE, verbose_name='والد')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='کاربر')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')
    text = models.TextField(verbose_name='متن نظر')

    def __str__(self):
        return str(self.user)

    class Meta:
        verbose_name = 'نظر مقاله'
        verbose_name_plural = 'نظرات مقاله'

article_module/templates/article_module/includes/article_comments_partial.html
{% load poll_extras %}

<h2> نظرات ({{ comments_count }})</h2>
<ul class="media-list">
    {% for comment in comments %}
        <li class="media" id="single_comment_box_{{ comment.id }}">
            <a class="pull-right" href="#">
                <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
            </a>
            <div class="media-body">
                <ul class="sinlge-post-meta">
                    <li><i class="fa fa-user"></i>{{ comment.user }}</li>
                    <li><i class="fa fa-clock-o"></i> {{ comment.create_date | time }}</li>
                    <li>
                        <i class="fa fa-calendar"></i> {{ comment.create_date|show_jalali_date }}
                    </li>
                </ul>
                <p>
                    {{ comment.text }}
                </p>
                <a class="btn btn-primary" onclick="fillParentId({{ comment.id }})"><i
                        class="fa fa-reply"></i>پاسـخ</a>
            </div>
        </li>

        {% for sub_comment in comment.articlecomment_set.all %}
            <li class="media second-media" id="single_comment_box_{{ comment.id }}">
                <a class="pull-right" href="#">
                    <img class="media-object" src="/static/images/blog/Customer.jpg" alt="">
                </a>
                <div class="media-body">
                    <ul class="sinlge-post-meta">
                        <li><i class="fa fa-user"></i>{{ sub_comment.user }}</li>
                        <li><i class="fa fa-clock-o"></i> {{ sub_comment.create_date | time }}
                        </li>
                        <li>
                            <i class="fa fa-calendar"></i> {{ sub_comment.create_date|show_jalali_date }}
                        </li>
                    </ul>
                    <p>
                        {{ sub_comment.text }}
                    </p>
                </div>
            </li>
        {% endfor %}
    {% endfor %}

</ul>